### ISSUE TITLE
Suggestions - tooltip at cursor - hide specific items - additional option for item switch rules

### ISSUE THREAD

**Issue by Wushengg** [RagedUnicorn/wow-gearmenu#11]
1. Having the option to have tooltips at the mouse cursor would be a nice QoL option.

2. Being able to blacklist/hide specific gear pieces would be handy. Some classes carry a lot of extra gear that provide unnecessary clutter (like healing + pvp gear). Being able to hide some of the healing pieces you'd never want to quickswap would make things cleaner.

Making sure it can detect the difference between two identical items but with two different enchants would be something to keep in mind. 

Itemrack got a good implementation of this if you're unsure what I mean.

3. Currently when you make a item switch rule the items swap even when the item doesn't successfully activate which can be an issue in some situations. For example making it possible to only change from skull of impending doom to another item after 9 seconds **if** skull activated in the first place.

**Comment by phendrome** [comment]
1. In the new upcoming version, and you use for example TinyTip you can set it be at your cursor (I recommend sticky) -- since it is not using its own tooltips anymore.
2. That's a nice idea regarding blacklisting specific items even when they are in your bag. You can obviously "hide" items having them in your bank but that's an unnecessary step.

**Comment by RagedUnicorn** [comment]
Hi guys,

Not sure if you saw already but what you can do currently is at least filter by item quality. This should help filter out "garbage" items.

Blacklisting/Hiding does sound like a good idea as well. I however think it will be quite a lot of work which I will not put into the addon anymore because the addon has to be rewritten for classic wow anyway.

Regards,
RagedUnicorn

**Comment by phendrome** [comment]
> Hi guys,
> 
> Not sure if you saw already but what you can do currently is at least filter by item quality. This should help filter out "garbage" items.
> 
> Blacklisting/Hiding does sound like a good idea as well. I however think it will be quite a lot of work which I will not put into the addon anymore because the addon has to be rewritten for classic wow anyway.
> 
> Regards,
> RagedUnicorn

Very true. This should definitely do for now, it's more than enough. It does sound good but definitely not a priority at all.

**Comment by RagedUnicorn** [comment]
Closing this then :)
