### ISSUE TITLE
[GearMenu 1.2] Not Locked When Logging In (Even If It Is Checked)

### ISSUE THREAD

**Issue by phendrome** [RagedUnicorn/wow-gearmenu#12]
Hey,

Using the latest branch of GearMenu at the moment (1.2).

When logging in it becomes unlocked every time. I have to go into option and press the lock window twice (disable & enable) to lock it.  _Using different textures hence the darkened icons_

See screenshots:
![trinketmenu](https://user-images.githubusercontent.com/2565750/48420152-07e01900-e75a-11e8-8970-b9f2153ce144.PNG)
![tm2](https://user-images.githubusercontent.com/2565750/48420151-07e01900-e75a-11e8-8643-124deafc5e87.PNG)

**Comment by RagedUnicorn** [comment]
Hi,

I can't seem to reproduce this issue. Can you try two things

Delete the following files if present:
 WTF\Account\ACCOUNTNAME\SavedVariables\GearMenu.lua
 WTF\Account\ACCOUNTNAME\SavedVariables\GearMenu.lua.bak

They were created due to a missunderstanding on my side how addon variables work. They are both not needed.

If this does not work can you copy and paste the content of:

WTF\Account\ACCOUNTNAME\RealmName\CharacterName\SavedVariables\GearMenu.lua

Cheers,
RagedUnicorn

**Comment by phendrome** [comment]
Yup it fixes it! Thank you.

Slightly OT... using the latest branch has the debugging in the chat enabled. How do you disable it?

![chat](https://user-images.githubusercontent.com/2565750/48457223-2bd74500-e7c2-11e8-9bbc-820c55706614.PNG)

**Comment by RagedUnicorn** [comment]
Hi @phendrome 

To remove those messages have a look into `Code/GM_Environment.lua` and change `LOG_LEVEL = 4,`

to `LOG_LEVEL = 1,` and also `LOG_EVENT = true`to `LOG_EVENT = false`.

E.g.

```lua
GM_ENVIRONMENT = {
  ADDON_NAME = "GearMenu",
  ADDON_NAME_SHORT = "GM",
  ADDON_VERSION = "1.2.0",
  ADDON_IDENTIFIER = "com.ragedunicorn.gearmenu",
  LOG_LEVEL = 1,
  LOG_EVENT = false
}
```
