### ISSUE TITLE
GearMenu chat spam

### ISSUE THREAD

**Issue by valynor** [RagedUnicorn/wow-gearmenu#14]
Just installed GearMenu for the first time. It works as advertised but it is generating an *insane* amount of chat spam. Every mouseover on the GM buttons produces several lines of text (e.g. GM: starting timer, GM: stopping timer etc pp). 

I can only assume this has something to do with pfUI but I didn't find any option in either addon to stop this behaviour.  Help! ;-)

**Comment by RagedUnicorn** [comment]
Hi @valynor,

Those are debug messages that are intended for the developer (mostly me). If you download the addon from the releases tab (which I recommend) you will always get a version that is ready for the player. In this case the log messages will be already deactivated.

Otherwise you will have to do this manullay by following these steps:

To remove those messages have a look into Code/GM_Environment.lua and change LOG_LEVEL = 4,

to LOG_LEVEL = 1, and also LOG_EVENT = true to LOG_EVENT = false.

E.g.

```
GM_ENVIRONMENT = {
  ADDON_NAME = "GearMenu",
  ADDON_NAME_SHORT = "GM",
  ADDON_VERSION = "1.2.0",
  ADDON_IDENTIFIER = "com.ragedunicorn.gearmenu",
  LOG_LEVEL = 1,
  LOG_EVENT = false
}
```

Cheers RagedUnicorn

**Comment by RagedUnicorn** [comment]
Going to close this then :)
