### ISSUE TITLE
[request] set approach

### ISSUE THREAD

**Issue by Altoholic** [RagedUnicorn/wow-gearmenu#7]
Hi

Will we ever have the possibility to make sets of gear, like outfitter/itemrack do, for the sake of having only one addon for taking care of all our gear needs ?
But as it's a very different thing of managing usable pieces of gear, i'll perfectly understand if your answer is "no".

**Comment by RagedUnicorn** [comment]
Hi,
while I like the addon outfitter the answer is indeed no :( sorry. I'm not trying to build an outfitter addon. The goal of gearmenu is to be a fast itemswitch addon for combat situations instead of switching complete sets of gear.

I also understand that you don't like having multiple addons doing similar things. However I prefer to keep addons small and manageable in regards of development.

Thank you for understanding

Regards,
RagedUnicorn

**Comment by Wushengg** [comment]
> The goal of gearmenu is to be a **fast itemswitch addon** for combat situations instead of switching complete sets of gear.

Would you consider adding some more item slots if that's the intention? For some classes in certain situations there is still a need for quickly switching 2 item slots even though one of the slots might not have any active items.

For example as a druid with only the blue pvp set I often find myself swapping either boots and leg slots to maintain the 4p set bonus.

No addon support for legs is the main thing keeping me from replacing itemrack with gearmenu and I think its possible other classes might have the same issue, but perhaps with other slots.

**Comment by Altoholic** [comment]
I remember a cape that have a slow fall effect. A rogue quest, iirc.

**Comment by RagedUnicorn** [comment]
Hi,

I certainly do. My initial goal was to support slots that have items that are usable but then afterwards you usually want to switch back to another item. I'm still missing some slots the cape is a good example that I would want myself for the slow fall cape.

https://classicdb.ch/?item=10606

I will certainly consider other slots as well. I guess in the end why not support all of the slots :) I should have some time during november and will see if I can start adding more supported slots for the next version

Regards,
RagedUnicorn

**Comment by Wushengg** [comment]
That sounds great! I'll be looking forward to finally replace itemrack for good.

Also the legs slot does actually have 1 active item https://classicdb.ch/?item=14554

**Comment by RagedUnicorn** [comment]
Hi @Wushengg and @Altoholic just a quick heads up. I added support for more slots.

These are the supported slots as of now:

HeadSlot | Head/Helmet slot
-- | --
NeckSlot | Neck slot
ShoulderSlot | Shoulder slot
ChestSlot | Chest/Robe slot
WaistSlot | Waist/Belt slot
LegsSlot | Legs slot
FeetSlot | Feet/Boots slot
WristSlot | Wrist/Bracers slot
HandsSlot | Hands slot
Finger0Slot | First/Upper ring slot
Finger1Slot | Second/Upper ring slot
Trinket0Slot | First/Upper trinket slot
Trinket1Slot | Second/Lower trinket slot
BackSlot | Back/Cloack slot slot
MainhandSlot | Main-hand slot
SecondaryHandSlot | Secondary-hand/Off-hand slot

It is also possible to have 10 active slots at the same time (previously 7). I did some testing and so far it looks good. If you have some time for testing as well I would be glad :)

Regards,
RagedUnicorn

**Comment by Wushengg** [comment]
Seems to work fine and not generate any errors. Just 2 minor things.

1. Currently its only possible to keybind 7 slots and not all 10.
2. The chat window in getting spammed by purple and green chat messages. I guess its intentional since it's not a release version, but thought I should mention anyway.

**Comment by RagedUnicorn** [comment]
Hi @Wushengg 

Thanks for your efforts.

1. I indeed forgot about this. Fixed in 9a1b316702fd1726575eddc7d982aef89690a931
2. This is indeed not the case in the release version. Those messages are for debugging during development.

I will test a bit more myself and then release 1.2.0 in the next days.
